FROM golang:1.15.1-alpine3.12 AS builder
RUN apk --update add ca-certificates tzdata
COPY . /app

FROM scratch
ENV TZ=Europe/Berlin
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY bin/main /
CMD ["/main"]
