apiVersion: v1
kind: Service
metadata:
  name: amazon-scrapper-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: amazon-scrapper-service
  type: NodePort
